# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField(default=0)),
                ('post_author', models.CharField(max_length=255)),
                ('post_date', models.DateTimeField(verbose_name='date published')),
                ('post_content', models.TextField()),
                ('post_title', models.TextField(max_length=1000)),
                ('post_status', models.CharField(max_length=20)),
                ('comment_status', models.CharField(max_length=20)),
                ('post_password', models.CharField(max_length=255)),
                ('post_name', models.CharField(max_length=200)),
                ('post_modified', models.DateTimeField(verbose_name='date modified')),
                ('post_type', models.CharField(default='post', max_length=20)),
                ('comment_count', models.IntegerField(default=0)),
                ('category_ID2', models.IntegerField()),
            ],
        ),
    ]
