# Generated by Django 2.0.7 on 2018-07-29 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('category_ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('category_level', models.IntegerField()),
                ('category_line', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('comment_ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('comment_post_ID', models.BigIntegerField(default=0)),
                ('comment_author', models.CharField(max_length=255)),
                ('comment_author_email', models.CharField(default='', max_length=100)),
                ('comment_date', models.DateTimeField(default=datetime.datetime.now)),
                ('comment_date_gmt', models.DateTimeField(default=datetime.datetime.now)),
                ('comment_content', models.TextField(default=datetime.datetime.now)),
                ('comment_type', models.CharField(default='', max_length=20)),
                ('user_id', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='posts',
            fields=[
                ('ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('post_author', models.CharField(max_length=20)),
                ('post_date', models.DateTimeField(default=datetime.datetime.now)),
                ('post_content', models.TextField()),
                ('post_title', models.TextField()),
                ('post_status', models.CharField(default='publish', max_length=20)),
                ('comment_status', models.CharField(default='open', max_length=20)),
                ('post_password', models.CharField(default='', max_length=255)),
                ('post_name', models.CharField(default='', max_length=250)),
                ('post_modified', models.DateTimeField(default=datetime.datetime.now)),
                ('post_type', models.CharField(default='post', max_length=20)),
                ('comment_count', models.BigIntegerField(default=0)),
                ('category_ID2', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_login', models.CharField(default='', max_length=60)),
                ('user_pass', models.CharField(default='', max_length=255)),
                ('user_nickname', models.CharField(default='', max_length=50)),
                ('user_email', models.CharField(default='', max_length=100)),
                ('user_registered', models.DateTimeField(default=datetime.datetime.now)),
                ('user_status', models.IntegerField(default=0)),
                ('display_name', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
